package:
  name: ncbi-ngs-sdk
  version: 2.9.1

build:
  number: 0

source:
  url: https://github.com/ncbi/ngs/archive/2.9.1.tar.gz
  sha256: c24c93bd70ed198a44c6b9dba0d6704edc90f228f832f2fef21fa5342303fc50

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - perl
    - libiconv
    - libxml2

test:
  commands:
    - test -e ${PREFIX}/lib64/libngs-sdk.so # [not osx]
    - test -e ${PREFIX}/lib64/libngs-sdk.dylib # [osx]

about:
  home: https://github.com/ncbi/ngs
  license: Public Domain
  license_file: LICENSE
  summary: NGS is a new, domain-specific API for accessing reads, alignments and pileups produced from Next Generation Sequencing.
