package:
  name: iqtree
  version: 2.0.4

source:
  git_url: https://github.com/Cibiv/IQ-TREE
  git_tag: v2.0.4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost-cpp
    - eigen
    - zlib
  run:
    - zlib

test:
  commands:
    - iqtree2

about:
  home: http://www.iqtree.org/
  summary: Efficient phylogenomic software by maximum likelihood
  license: GPLv2
  license_file: LICENSE
