package:
  name: iqtree
  version: 1.6.7.1

source:
  git_url: https://github.com/Cibiv/IQ-TREE
  git_tag: v1.6.7.1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - eigen
    - zlib
  run:
    - zlib

test:
  commands:
    - iqtree

about:
  home: http://www.iqtree.org/
  summary: Efficient phylogenomic software by maximum likelihood
  license: GPLv2
  license_file: LICENSE
