{% set name = "hyphy-python" %}
{% set version = "0.1.9" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c088a5c1e2bb4c3612abcc3c580e329fe5c6e06c2dc8b408abfe112220e5567e" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - curl
  run:
    - python
    - setuptools
    - curl

test:
  imports:
    - HyPhy

about:
  home: http://github.com/veg/hyphy
  summary: HyPhy package interface library
  license: MIT
