package:
  name: fastaq
  version: 3.15.0

source:
  git_url: https://github.com/sanger-pathogens/Fastaq
  git_tag: v3.15.0

build:
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - pyfastaq
  commands:
    - fastaq version

about:
  home: https://github.com/sanger-pathogens/Fastaq
  summary: Python3 scripts to manipulate FASTA and FASTQ files
  license: GPLv3
  license_file: LICENSE
