package:
  name: bowtie2
  version: 2.3.5.1

source:
  fn: bowtie2-2.3.5.1.tar.gz
  url: https://github.com/BenLangmead/bowtie2/archive/v2.3.5.1.tar.gz
  sha256: 86a018af1090900c160a0990cc106569805aa64a3ec8708e1d2127839e4a94b4

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - zlib
  run:
    - python
    - perl
    - zlib

test:
  commands:
    - bowtie2 --help
    - bowtie2-align-l --help
    - bowtie2-align-s --help
    - bowtie2-build --help
    - bowtie2-build-l --help
    - bowtie2-build-s --help
    - bowtie2-inspect --help
    - bowtie2-inspect-l --help
    - bowtie2-inspect-s --help

about:
  home: http://bowtie-bio.sourceforge.net/bowtie2/index.shtml
  summary: Fast and sensitive read alignment
  license: GPLv3
  license_file: LICENSE
