package:
  name: iva
  version: 1.0.9

source:
  git_url: https://github.com/sanger-pathogens/iva
  git_tag: v1.0.9

build:
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - networkx
    - fastaq ==3.15.0
    - kmc ==3.0.0
    - mummer ==3.23
    - pysam ==0.14.1
    - samtools ==1.3.1
    - smalt ==0.7.6
  run:
    - python
    - setuptools
    - networkx
    - fastaq ==3.15.0
    - kmc ==3.0.0
    - mummer ==3.23
    - pysam ==0.14.1
    - samtools ==1.3.1
    - smalt ==0.7.6

test:
  commands:
    - iva --version

about:
  home: https://github.com/sanger-pathogens/iva
  summary: de novo virus assembler of Illumina paired reads
  license: GPLv3
  license_file: LICENSE
