package:
  name: bioconductor-ggtree
  version: 3.8

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-ape
    - r-ggplot2
    - r-magrittr
    - r-tidyverse
  run:
    - r-base
    - r-ape
    - r-ggplot2
    - r-magrittr
    - r-tidyverse

test:
  commands:
    - '$R -e "library(ggtree)"'

about:
  home: http://bioconductor.org/packages/release/bioc/html/ggtree.html
  summary: an R package for visualization and annotation of phylogenetic trees with their covariates and other associated data
  license: Artistic-2.0
