{% set name = "biopython" %}
{% set version = "1.73" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "70c5cc27dc61c23d18bb33b6d38d70edc4b926033aea3b7434737c731c94a5e0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - Bio
    - Bio.Align
    - Bio.Align.Applications
    - Bio.AlignIO
    - Bio.Alphabet
    - Bio.Application
    - Bio.Blast
    - Bio.CAPS
    - Bio.Compass
    - Bio.Crystal
    - Bio.Data
    - Bio.Emboss
    - Bio.Entrez
    - Bio.ExPASy
    - Bio.FSSP
    - Bio.GenBank
    - Bio.Geo
    - Bio.HMM
    - Bio.KEGG
    - Bio.KEGG.Compound
    - Bio.KEGG.Enzyme
    - Bio.KEGG.Gene
    - Bio.KEGG.KGML
    - Bio.KEGG.Map
    - Bio.Medline
    - Bio.NMR
    - Bio.Nexus
    - Bio.PDB
    - Bio.PDB.QCPSuperimposer
    - Bio.Pathway
    - Bio.Pathway.Rep
    - Bio.Phylo
    - Bio.Phylo.Applications
    - Bio.Phylo.PAML
    - Bio.PopGen
    - Bio.PopGen.GenePop
    - Bio.Restriction
    - Bio.SCOP
    - Bio.SVDSuperimposer
    - Bio.SearchIO
    - Bio.SearchIO.BlastIO
    - Bio.SearchIO.ExonerateIO
    - Bio.SearchIO.HmmerIO
    - Bio.SearchIO.InterproscanIO
    - Bio.SearchIO._legacy
    - Bio.SearchIO._model
    - Bio.SeqIO
    - Bio.SeqUtils
    - Bio.Sequencing
    - Bio.Sequencing.Applications
    - Bio.Statistics
    - Bio.SubsMat
    - Bio.SwissProt
    - Bio.TogoWS
    - Bio.UniGene
    - Bio.UniProt
    - Bio.Wise
    - Bio._py3k
    - Bio.codonalign
    - Bio.motifs
    - Bio.motifs.applications
    - Bio.motifs.jaspar
    - BioSQL

about:
  home: https://biopython.org/
  summary: Freely available tools for computational molecular biology.
  license: Other
  license_file: LICENSE.rst
