package:
  name: samtools
  version: 1.3.1

source:
  fn: samtools-1.3.1.tar.bz2
  url: https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
  md5: a7471aa5a1eb7fc9cc4c6491d73c2d88

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - curl
    - zlib
  run:
    - curl
    - perl
    - zlib

test:
  commands:
    - samtools --help

about:
  home: https://github.com/samtools/samtools
  summary: Tools for dealing with SAM, BAM and CRAM files
  license: MIT
  license_file: LICENSE
