package:
  name: bioext
  version: 0.19.4

source:
  git_url: https://github.com/veg/bioext
  git_tag: 0.19.4

build:
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - biopython
    - cython
    - joblib
    - numpy
    - pysam
    - scipy
    - six
  run:
    - python
    - setuptools
    - biopython
    - cython
    - joblib
    - numpy
    - pysam
    - scipy
    - six

test:
  imports:
    - BioExt
  commands:
    - bam2fna -h

about:
  home: https://github.com/veg/BioExt
  summary: A few handy bioinformatics tools not already within BioPython
  license: GPLv3
