{% set name = "hivtrace" %}
{% set version = "0.4.4" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "699e46782ca05ce2d90b4f0d8ca1233e73437524b487433c15402d662c7bd40b" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - hivtrace = hivtrace.hivtrace:main
    - hivtrace_strip_drams = hivtrace.strip_drams:main
    - hivtrace_viz = hivtrace.hivtraceviz:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - tornado
    - hivclustering ==1.2.8
  run:
    - python
    - setuptools
    - tornado
    - hivclustering ==1.2.8

test:
  imports:
    - hivtrace
  commands:
    - hivtrace --help
    - hivtrace_strip_drams --help
    - hivtrace_viz --help
  requires:
    - nose

about:
  home: http://www.hivtrace.org
  summary: Reconstruction and analysis of HIV-1 molecular transmission networks
  license: MIT
