package:
  name: pysam
  version: 0.14.1

source:
  git_url: https://github.com/pysam-developers/pysam
  git_tag: v0.14.1

build:
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - bzip2
    - xz
    - zlib
  run:
    - python
    - setuptools
    - bzip2
    - xz
    - zlib

test:
  imports:
    - pysam

about:
  home: https://github.com/pysam-developers/pysam
  summary: Python module for reading and manipulating SAM/BAM/VCF/BCF files
  license: MIT
  license_file: COPYING
