{% set name = "PhyML" %}
{% set version = "3.3.20200621" %}
{% set sha256 = "a8243923ee08c74cab609a4b086ade66c6156fc2b24450e2a500108dc644c867" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/stephaneguindon/{{ name | lower }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
test:
  commands:
    - phyml --help | grep "PhyML {{ version }}"
    - phytime --help | grep "PhyTime {{ version }}"

about:
  home: http://www.atgc-montpellier.fr/phyml/
  dev_url: https://github.com/stephaneguindon/phyml/
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING 
  summary: Phylogenetic estimation using (Maximum) Likelihood
